{% set version = "1.2.2" %}

package:
  name: mizuroute
  version: {{ version }}

source:
  url: https://github.com/ncar/mizuroute/archive/v{{ version }}.tar.gz
  sha256: 0cf0edb4264963e848c571575781a345d6492b2e1d2b4a46ef5f00ba617b3c9b
  patches:
    - make.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}
  host:
    - netcdf-fortran
  run:
    - netcdf-fortran

test:
  commands:
    - test -f $PREFIX/bin/route_runoff.exe

about:
  home: http://github.com/ncar/mizuroute
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'Stand-alone streamflow routing model '

  description: |
    Stand-alone mizuRoute is a post-processor of runoff output from a hydrologic model
    or Land surface model to produce streamflow estimates in the river network provided
    by a user. The tool was developed for the large scale, network based river routing
    (e.g., river network over contiguous United States), but works for gridded river
    network as well.
  doc_url: http://mizuroute.readthedocs.io/
  dev_url: https://github.com/ncar/mizuroute

extra:
  recipe-maintainers:
    - arbennett
    - bartnijssen
    - nmizukami
    - ShervanGharari
